### Create a valid user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpassword"
}

###

### Create user with short username (should fail)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ab",
  "name": "Test User",
  "password": "testpassword"
}

###

### Create user with short password (should fail)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser2",
  "name": "Test User 2",
  "password": "ab"
}

###

### Create user without username (should fail)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "name": "Test User",
  "password": "testpassword"
}

###

### Create user without password (should fail)
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser3",
  "name": "Test User 3",
  "password": "testpassword"
}

###

### Get all users
GET http://localhost:3003/api/users

###

### Get all blogs
GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/


###

PUT http://localhost:3003/api/blogs/69043a745f3c89ebb713c9af
Content-Type: application/json

{
  "title": "Tutorial",
  "author": "John Doe",
  "url": "https://example.com/node",
  "likes": 25
}

###

DELETE http://localhost:3003/api/blogs/69043a745f3c89ebb713c9af