### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpassword"
}

###

### Create another user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "salainen"
}

###

### Get all users
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React Patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Go To Statement Considered Harmful",
  "author": "Edsger W. Dijkstra",
  "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
  "likes": 5
}

###

GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/blogs/


###

PUT http://localhost:3003/api/blogs/69043a745f3c89ebb713c9af
Content-Type: application/json

{
  "title": "Tutorial",
  "author": "John Doe",
  "url": "https://example.com/node",
  "likes": 25
}

###

DELETE http://localhost:3003/api/blogs/69043a745f3c89ebb713c9af